/// Beacon token name for the UTXO containing the global settings datum
pub const global_cfg_token: ByteArray = "GCFG"

/// Beacon token name for the UTXO containing the oracle settings datum
pub const oracle_cfg_token: ByteArray = "OCFG"

/// Beacon token name for UTXOs containing oracle price datum
pub const oracle_price_token: ByteArray = "OPRC"

/// Beacon token name for UTXO containing the protocol's audit datum
pub const audit_token: ByteArray = "AUDT"
